server:
  port: 8085

spring:
  application:
    name: gateway-adapter-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_gateway
    username: payflow
    password: payflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
