server:
  port: 8082

spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_ledger
    username: payflow
    password: payflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledger-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
